-- Habilitar extensión pgcrypto para gen_random_uuid() si no está habilitada
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================================
-- 1. CREACIÓN DE TABLAS (IDEMPOTENTE)
-- ==========================================

-- Tabla: users
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR UNIQUE NOT NULL,
    full_name VARCHAR,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Tabla: auth_codes
CREATE TABLE IF NOT EXISTS public.auth_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    otp_code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN DEFAULT false
);

-- Tabla: device_assignments
CREATE TABLE IF NOT EXISTS public.device_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    node_id VARCHAR NOT NULL,
    alias VARCHAR,
    assigned_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT unique_user_node UNIQUE (user_id, node_id)
);

-- Tabla: telemetria_indoor
CREATE TABLE IF NOT EXISTS public.telemetria_indoor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    node_id VARCHAR NOT NULL,
    sensor_id VARCHAR NOT NULL,
    temperatura REAL,
    humedad_ambiente REAL,
    humedad_suelo REAL,
    ph REAL,
    estado_actuadores VARCHAR
);

-- ==========================================
-- 2. OPTIMIZACIÓN (ÍNDICES)
-- ==========================================

CREATE INDEX IF NOT EXISTS telemetria_indoor_created_at_idx 
ON public.telemetria_indoor (created_at DESC);

CREATE INDEX IF NOT EXISTS telemetria_indoor_node_sensor_idx 
ON public.telemetria_indoor (node_id, sensor_id);

CREATE INDEX IF NOT EXISTS auth_codes_user_used_idx 
ON public.auth_codes (user_id, used);

-- ==========================================
-- 3. INSERCIÓN DE DATOS SEMILLA (SEED DATA)
-- ==========================================

DO $$
DECLARE
    v_user_id UUID;
    v_admin_email VARCHAR := 'jhonattan.gonzalez.38@gmail.com';
    v_node_id VARCHAR := 'FOG_RPI_HIERBABUENA_01';
BEGIN
    -- Insertar/Actualizar Usuario Admin y obtener su ID
    INSERT INTO public.users (email, full_name)
    VALUES (v_admin_email, 'Jhonattan Gonzalez')
    ON CONFLICT (email) DO UPDATE 
    SET full_name = EXCLUDED.full_name
    RETURNING id INTO v_user_id;

    -- Precaución en caso de que RETURNING no asigne por coincidencia exacta según versión de Postgres
    IF v_user_id IS NULL THEN
        SELECT id INTO v_user_id FROM public.users WHERE email = v_admin_email;
    END IF;

    -- Insertar Asignación del Dispositivo (Gateway)
    INSERT INTO public.device_assignments (user_id, node_id, alias)
    VALUES (v_user_id, v_node_id, 'Cultivo Hierbabuena - Sede Principal')
    ON CONFLICT (user_id, node_id) DO UPDATE 
    SET alias = EXCLUDED.alias;

    -- Insertar Registros de Telemetría (Solo si no hay datos para este Gateway para evitar duplicados infinitos al re-ejecutar)
    IF NOT EXISTS (SELECT 1 FROM public.telemetria_indoor WHERE node_id = v_node_id LIMIT 1) THEN
        INSERT INTO public.telemetria_indoor (
            node_id, sensor_id, temperatura, humedad_ambiente, humedad_suelo, ph, estado_actuadores
        ) VALUES 
        (v_node_id, 'SENSOR_HIERBABUENA_01', 22.5, 65.0, 70.0, 6.2, '{"bomba": "ON", "ventilador": "OFF"}'),
        (v_node_id, 'SENSOR_HIERBABUENA_02', 23.1, 63.5, 68.5, 6.1, '{"bomba": "ON", "ventilador": "OFF"}');
    END IF;

END $$;
