-- ============================================================
--  001_init.sql — Esquema inicial en Neon PostgreSQL
--  VitalCrop AGW · Esquema inicial completo
--  Destino: neondb (PostgreSQL 18.4)
-- ============================================================
--  Notas de diseño:
--   · gen_random_uuid() es nativo desde PostgreSQL 13 — no hace
--     falta la extensión pgcrypto (verificado en el servidor).
--   · No se usan auth.uid() ni auth.role(): eran específicos de
--     otros proveedores. El aislamiento por usuario se hace en la API
--     mediante el JWT, no con RLS de base de datos.
--   · Idempotente: se puede re-ejecutar sin efectos secundarios.
-- ============================================================

-- ────────────────────────────────────────────────────────────
--  users — cuentas del dashboard privado
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email       VARCHAR NOT NULL UNIQUE,
    full_name   VARCHAR,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.users IS 'Usuarios del dashboard privado. Login passwordless por OTP.';

-- ────────────────────────────────────────────────────────────
--  auth_codes — códigos OTP de 6 dígitos (login passwordless)
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.auth_codes (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    otp_code    VARCHAR(6) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used        BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS auth_codes_user_used_idx
    ON public.auth_codes (user_id, used);

COMMENT ON TABLE public.auth_codes IS 'Códigos OTP temporales. Expiran a los 10 minutos.';

-- ────────────────────────────────────────────────────────────
--  gateways — Raspberry Pi (broker físico) asignada a un usuario
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gateways (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    gateway_id  VARCHAR NOT NULL,
    alias       VARCHAR,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT unique_user_gateway UNIQUE (user_id, gateway_id)
);

CREATE INDEX IF NOT EXISTS gateways_user_id_idx
    ON public.gateways (user_id);

COMMENT ON COLUMN public.gateways.gateway_id IS
    'Identificador lógico del gateway, ej. FOG_RPI_HIERBABUENA_01. Coincide con node_id en POST /api/telemetria.';

-- ────────────────────────────────────────────────────────────
--  edge_nodes — nodos ESP32 colgando de un gateway
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.edge_nodes (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    gateway_id  UUID NOT NULL REFERENCES public.gateways(id) ON DELETE CASCADE,
    sensor_id   VARCHAR NOT NULL,
    node_type   VARCHAR NOT NULL CHECK (node_type IN ('TIERRA', 'HIDROPONIA')),
    alias       VARCHAR,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT unique_gateway_sensor UNIQUE (gateway_id, sensor_id)
);

CREATE INDEX IF NOT EXISTS edge_nodes_gateway_id_idx
    ON public.edge_nodes (gateway_id);

COMMENT ON COLUMN public.edge_nodes.sensor_id IS
    'Identificador del hardware ESP32, ej. IoT-node-26.001. Coincide con sensor_id en POST /api/telemetria.';

-- ────────────────────────────────────────────────────────────
--  telemetria_indoor — serie temporal de telemetría
-- ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.telemetria_indoor (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    node_id             VARCHAR NOT NULL,   -- → gateways.gateway_id (join lógico)
    sensor_id           VARCHAR NOT NULL,   -- → edge_nodes.sensor_id (join lógico)

    temperatura         REAL,
    humedad_ambiente    REAL,
    humedad_suelo       REAL,
    ph                  REAL,               -- Retirado del alcance (MCD §6.4).
                                            -- La columna se conserva a propósito:
                                            -- reactivar el pH no debe requerir migración.
    estado_actuadores   VARCHAR,

    CONSTRAINT chk_temperatura      CHECK (temperatura      IS NULL OR temperatura      BETWEEN -40 AND 100),
    CONSTRAINT chk_humedad_ambiente CHECK (humedad_ambiente IS NULL OR humedad_ambiente BETWEEN   0 AND 100),
    CONSTRAINT chk_humedad_suelo    CHECK (humedad_suelo    IS NULL OR humedad_suelo    BETWEEN   0 AND 100),
    CONSTRAINT chk_ph               CHECK (ph               IS NULL OR ph               BETWEEN   0 AND  14)
);

-- Query principal del dashboard: filtrar por nodo, ordenar por tiempo desc
CREATE INDEX IF NOT EXISTS telemetria_indoor_node_time_idx
    ON public.telemetria_indoor (node_id, created_at DESC);

CREATE INDEX IF NOT EXISTS telemetria_indoor_created_at_idx
    ON public.telemetria_indoor (created_at DESC);

CREATE INDEX IF NOT EXISTS telemetria_indoor_node_sensor_idx
    ON public.telemetria_indoor (node_id, sensor_id);

COMMENT ON TABLE public.telemetria_indoor IS
    'Telemetría del cultivo indoor. created_at lo estampa la base de datos: el ESP32 no tiene reloj real (MCD §4.1).';

-- ────────────────────────────────────────────────────────────
--  Semilla — identificadores canónicos del MCD §10
-- ────────────────────────────────────────────────────────────
--  Corrige una inconsistencia heredada: la semilla
--  antigua registraba ESP32_TIERRA_01 / ESP32_HIDROPONIA_01,
--  que no existen en hardware. El nodo real es IoT-node-26.001.
-- ────────────────────────────────────────────────────────────
DO $$
DECLARE
    v_user_id      UUID;
    v_gateway_uuid UUID;
    v_email        VARCHAR := 'jhonattan.gonzalez.38@gmail.com';
    v_gateway_id   VARCHAR := 'FOG_RPI_HIERBABUENA_01';
BEGIN
    INSERT INTO public.users (email, full_name)
    VALUES (v_email, 'Jhonattan Gonzalez')
    ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name
    RETURNING id INTO v_user_id;

    IF v_user_id IS NULL THEN
        SELECT id INTO v_user_id FROM public.users WHERE email = v_email;
    END IF;

    INSERT INTO public.gateways (user_id, gateway_id, alias)
    VALUES (v_user_id, v_gateway_id, 'Raspberry Pi — Gateway Fog Principal')
    ON CONFLICT (user_id, gateway_id) DO UPDATE SET alias = EXCLUDED.alias
    RETURNING id INTO v_gateway_uuid;

    IF v_gateway_uuid IS NULL THEN
        SELECT id INTO v_gateway_uuid
        FROM public.gateways
        WHERE user_id = v_user_id AND gateway_id = v_gateway_id;
    END IF;

    -- Nodo real, el que está flasheado (config.h: DEVICE_ID)
    INSERT INTO public.edge_nodes (gateway_id, sensor_id, node_type, alias)
    VALUES (v_gateway_uuid, 'IoT-node-26.001', 'HIDROPONIA', 'Nodo HydroNode — hierbabuena indoor')
    ON CONFLICT (gateway_id, sensor_id) DO UPDATE
        SET alias = EXCLUDED.alias, node_type = EXCLUDED.node_type;

    RAISE NOTICE 'Semilla aplicada: user=% gateway=% nodo=IoT-node-26.001', v_email, v_gateway_id;
END $$;
