-- ============================================================
--  002_telecom.sql — Lo que hace falta para medir la red
-- ============================================================
--  El esquema 001 guarda cuatro variables agronómicas y nada más.
--  Con eso no se puede sostener el eje evaluativo del proyecto, que
--  es el desempeño de la cadena de telecomunicaciones (MCD §9): no
--  hay dónde poner el RSSI que ya viene en cada trama, ni la marca de
--  tiempo del gateway, ni la conductividad que el nodo mide desde la
--  v2.3.0 del firmware.
--
--  Esta migración añade tres cosas:
--
--    1. Las columnas que el nodo YA publica y se estaban descartando
--       en la ingesta.
--    2. `t_rx`, el instante en que la Raspberry recibió la trama.
--       Junto a `created_at` (cuando la nube la insertó) da la
--       latencia de subida por registro, sin instrumentación extra.
--    3. Dos tablas nuevas: muestras de red y eventos del nodo, que
--       son las que alimentan mapas de calor, distribuciones y el
--       cálculo de disponibilidad.
-- ============================================================

-- ── 1 · Telemetría: lo que se estaba tirando ──────────────────

ALTER TABLE public.telemetria_indoor
    ADD COLUMN IF NOT EXISTS rssi        SMALLINT,
    ADD COLUMN IF NOT EXISTS ec          REAL,
    ADD COLUMN IF NOT EXISTS tds         REAL,
    ADD COLUMN IF NOT EXISTS nivel_raw   INTEGER,
    ADD COLUMN IF NOT EXISTS agua        BOOLEAN,
    ADD COLUMN IF NOT EXISTS fw          VARCHAR(16),
    ADD COLUMN IF NOT EXISTS uptime_ms   BIGINT,
    ADD COLUMN IF NOT EXISTS periodo_ms  INTEGER,
    -- Instante de recepción en el gateway. Con created_at da la
    -- latencia de subida; y como el nodo no sella sus tramas todavía,
    -- es además la referencia temporal más fiable que existe hoy.
    ADD COLUMN IF NOT EXISTS t_rx        TIMESTAMPTZ;

COMMENT ON COLUMN public.telemetria_indoor.t_rx IS
    'Recepción en el gateway. created_at - t_rx = latencia de subida (MCD §9)';
COMMENT ON COLUMN public.telemetria_indoor.uptime_ms IS
    'Uptime del nodo. Su retroceso delata un reinicio; su salto entre '
    'tramas consecutivas, junto a periodo_ms, da la pérdida de mensajes';

-- Series temporales: casi toda consulta filtra por nodo y ordena por
-- tiempo. Sin este índice, cada gráfica del dashboard es un seq scan.
CREATE INDEX IF NOT EXISTS idx_telemetria_sensor_t
    ON public.telemetria_indoor (sensor_id, t_rx DESC);

CREATE INDEX IF NOT EXISTS idx_telemetria_t_rx
    ON public.telemetria_indoor (t_rx DESC);

-- ── 2 · Muestras de red ───────────────────────────────────────
--
--  Una fila por medida de red: sondas activas (ICMP, ida y vuelta
--  MQTT, HTTP) y métricas derivadas por ventana (pérdida, jitter).
--
--  Se guarda crudo y no agregado a propósito: los mapas de calor
--  hora × día y las distribuciones necesitan la muestra individual.
--  Agregar es barato en la consulta; desagregar es imposible.

CREATE TABLE IF NOT EXISTS public.net_muestras (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL,
    gateway_id  VARCHAR NOT NULL,
    sensor_id   VARCHAR,
    -- rtt_icmp | rtt_mqtt | rtt_http | latencia_subida | jitter
    -- | perdida_pct | rssi | disponibilidad
    metrica     VARCHAR(24) NOT NULL,
    valor       DOUBLE PRECISION NOT NULL,
    unidad      VARCHAR(12) NOT NULL DEFAULT 'ms',
    -- Contexto que explica el número: nº de muestras de la ventana,
    -- cadencia vigente, si el ahorro de WiFi estaba activo...
    detalle     JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_net_metrica_ts
    ON public.net_muestras (metrica, ts DESC);

CREATE INDEX IF NOT EXISTS idx_net_ts
    ON public.net_muestras (ts DESC);

-- ── 3 · Eventos del nodo ──────────────────────────────────────
--
--  Espejo en la nube de node_events de la Raspberry: caídas,
--  reconexiones, discrepancias de programa y ciclos de riego.
--
--  Es lo que permite calcular disponibilidad y MTTR sin depender del
--  journal de systemd, que rota y se pierde.

CREATE TABLE IF NOT EXISTS public.node_eventos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL,
    gateway_id  VARCHAR NOT NULL,
    sensor_id   VARCHAR,
    evento      VARCHAR(40) NOT NULL,
    detalle     JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Un mismo evento reenviado por un reintento no puede duplicarse:
    -- el par (nodo, instante, tipo) lo identifica.
    CONSTRAINT uq_evento UNIQUE (sensor_id, ts, evento)
);

CREATE INDEX IF NOT EXISTS idx_eventos_ts
    ON public.node_eventos (ts DESC);

CREATE INDEX IF NOT EXISTS idx_eventos_tipo_ts
    ON public.node_eventos (evento, ts DESC);

-- ── 4 · Vistas para el panel ──────────────────────────────────
--
--  El dashboard no debería reimplementar estas agregaciones en
--  TypeScript: si la definición de "pérdida" vive en el frontend, el
--  día que cambie habrá dos definiciones distintas en el sistema.

-- Mapa de calor hora × día. Una fila por celda, lista para pintar.
CREATE OR REPLACE VIEW public.v_rssi_hora_dia AS
SELECT
    date_trunc('day', t_rx)::date       AS dia,
    EXTRACT(hour FROM t_rx)::int        AS hora,
    sensor_id,
    ROUND(AVG(rssi)::numeric, 1)        AS rssi_medio,
    MIN(rssi)                           AS rssi_min,
    MAX(rssi)                           AS rssi_max,
    COUNT(*)                            AS muestras
FROM public.telemetria_indoor
WHERE rssi IS NOT NULL AND t_rx IS NOT NULL
GROUP BY 1, 2, 3;

-- Latencia de subida: lo que tardó cada trama desde que la Pi la
-- recibió hasta que la nube la escribió.
CREATE OR REPLACE VIEW public.v_latencia_subida AS
SELECT
    t_rx,
    sensor_id,
    EXTRACT(EPOCH FROM (created_at - t_rx)) * 1000 AS latencia_ms
FROM public.telemetria_indoor
WHERE t_rx IS NOT NULL AND created_at > t_rx;

-- Cadencia real de llegada, para jitter. LAG sobre la serie por nodo.
CREATE OR REPLACE VIEW public.v_intervalos AS
SELECT
    sensor_id,
    t_rx,
    periodo_ms,
    uptime_ms,
    EXTRACT(EPOCH FROM (t_rx - LAG(t_rx) OVER (PARTITION BY sensor_id ORDER BY t_rx))) AS intervalo_s,
    uptime_ms - LAG(uptime_ms) OVER (PARTITION BY sensor_id ORDER BY t_rx)             AS d_uptime_ms
FROM public.telemetria_indoor
WHERE t_rx IS NOT NULL;
