-- ============================================================
--  004_comandos.sql — La tabla de órdenes
-- ============================================================
--  El anteproyecto compromete "recibir órdenes revisando una tabla de
--  órdenes" y el dashboard ya tiene una página de comandos que la
--  invoca. No existía por ningún lado (deuda 7.10 del MCD).
--
--  El mando es asíncrono por necesidad, no por comodidad: la nube no
--  puede hablarle al ESP32, que vive detrás del NAT del gateway y en
--  una red aislada sin salida. El único que puede alcanzarlo es la
--  Raspberry. Así que la web encola aquí, el gateway consulta y
--  entrega, y el acuse vuelve a esta misma fila.
--
--  Tener el estado en la tabla —y no solo el hecho de haber pulsado un
--  botón— es lo que permite distinguir "lo pedí" de "llegó".
-- ============================================================

CREATE TABLE IF NOT EXISTS public.comandos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    sensor_id     VARCHAR NOT NULL,
    -- El JSON tal como lo entiende el firmware. Sin traducción: el
    -- contrato canónico es el suyo (MCD §6.5) y una capa intermedia
    -- sería un sitio más donde desincronizarse.
    comando       JSONB NOT NULL,
    estado        VARCHAR(12) NOT NULL DEFAULT 'pendiente'
                  CHECK (estado IN ('pendiente', 'entregado', 'fallido', 'cancelado')),
    entregado_en  TIMESTAMPTZ,
    resultado     TEXT,
    nota          VARCHAR(255),
    creado_por    VARCHAR
);

-- El gateway consulta pendientes cada pocos segundos: ese es el acceso
-- caliente y el que debe ser barato.
CREATE INDEX IF NOT EXISTS idx_comandos_pendientes
    ON public.comandos (estado, creado_en)
    WHERE estado = 'pendiente';

CREATE INDEX IF NOT EXISTS idx_comandos_creado
    ON public.comandos (creado_en DESC);

COMMENT ON TABLE public.comandos IS
    'Cola de órdenes nube -> gateway -> nodo. La nube nunca alcanza al '
    'ESP32 directamente: está en la red aislada del cultivo.';
